# Generated by Django 3.0.2 on 2020-01-26 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=200, verbose_name='Numero')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cilindraje', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cilindraje')),
                ('tiempos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiempos')),
                ('placa', models.CharField(max_length=200, verbose_name='Placa')),
                ('modelo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo')),
                ('puertas', models.IntegerField(blank=True, max_length=200, null=True, verbose_name='Puertas')),
                ('foto', models.FileField(upload_to='', verbose_name='Foto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoVehiculo', verbose_name='Tipo vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha ingreso')),
                ('celda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Celda', verbose_name='Celda')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Vehiculo', verbose_name='Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=200, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.TipoDocumento', verbose_name='Tipo documento')),
            ],
        ),
    ]
