# Generated by Django 3.0.2 on 2020-01-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200126_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='celda',
            name='ocupada',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
