# Generated by Django 3.0.2 on 2020-01-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_celda_ocupada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='cars', verbose_name='Foto'),
        ),
    ]
