# Generated by Django 3.0.2 on 2020-01-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200129_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='gestion/media', verbose_name='Foto'),
        ),
    ]
