# Generated by Django 3.0.2 on 2020-01-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20200129_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha salida'),
        ),
    ]
