# Generated by Django 3.0.2 on 2020-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_registro_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='gestion/static/media', verbose_name='Foto'),
        ),
    ]
