# Generated by Django 3.0.2 on 2020-01-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20200129_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos', verbose_name='Foto'),
        ),
    ]
